-- Group chats. A conversation is now DIRECT (the existing one-to-one pair) or GROUP (any number of members, tracked in conversation_members).
-- Direct conversations are untouched: they keep their pair columns, their per-side "cleared before" markers and Message.read_at.
-- A group has no pair, so the pair columns become nullable; the check below keeps each kind consistent.
ALTER TABLE public.conversations
    ALTER COLUMN user_one_id DROP NOT NULL,
    ALTER COLUMN user_two_id DROP NOT NULL,
    ADD COLUMN type character varying(10) NOT NULL DEFAULT 'DIRECT',
    ADD COLUMN title character varying(100),
    ADD COLUMN created_by_id bigint REFERENCES public.users(id);

ALTER TABLE public.conversations
    ADD CONSTRAINT ck_conversations_type CHECK (
        (type = 'DIRECT' AND user_one_id IS NOT NULL AND user_two_id IS NOT NULL)
        OR (type = 'GROUP' AND user_one_id IS NULL AND user_two_id IS NULL));

-- One row per member of a group. cleared_before: messages up to this id are hidden from the member (history from before they joined, or that
-- they deleted for themselves). last_read_message_id: everything up to it counts as read (a shared messages.read_at cannot work with many readers).
CREATE TABLE public.conversation_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id bigint NOT NULL REFERENCES public.conversations(id),
    user_id bigint NOT NULL REFERENCES public.users(id),
    role character varying(10) NOT NULL,
    joined_at timestamp(6) with time zone NOT NULL,
    cleared_before bigint NOT NULL DEFAULT 0,
    last_read_message_id bigint NOT NULL DEFAULT 0,
    CONSTRAINT uk_conversation_members UNIQUE (conversation_id, user_id)
);

CREATE INDEX idx_conversation_members_user ON public.conversation_members USING btree (user_id);
