-- Words and phrases a user does not want to see: posts containing one (whole word, any case) are left out of their timelines and searches.
CREATE TABLE public.muted_words (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users (id),
    word character varying(50) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_muted_words_user_word UNIQUE (user_id, word)
);
