-- A poll attached to a top-level post: 2 to 4 options, one vote per person, closes at expires_at.
CREATE TABLE public.polls (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id bigint NOT NULL REFERENCES public.posts (id),
    expires_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_polls_post UNIQUE (post_id)
);

CREATE TABLE public.poll_options (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id bigint NOT NULL REFERENCES public.polls (id),
    position integer NOT NULL,
    text character varying(25) NOT NULL,
    vote_count integer NOT NULL DEFAULT 0
);

CREATE INDEX idx_poll_options_poll ON public.poll_options USING btree (poll_id, position);

CREATE TABLE public.poll_votes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id bigint NOT NULL REFERENCES public.polls (id),
    option_id bigint NOT NULL REFERENCES public.poll_options (id),
    user_id bigint NOT NULL REFERENCES public.users (id),
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_poll_votes_voter UNIQUE (poll_id, user_id)
);

CREATE INDEX idx_poll_votes_user ON public.poll_votes USING btree (user_id);
