--
-- PostgreSQL database dump
--

-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;

--
-- Name: blocks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.blocks (
    blocked_id bigint NOT NULL,
    blocker_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL
);

--
-- Name: blocks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.blocks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blocks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: bookmarks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookmarks (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    post_id bigint NOT NULL,
    user_id bigint NOT NULL
);

--
-- Name: bookmarks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bookmarks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookmarks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: conversations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.conversations (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone DEFAULT now() NOT NULL,
    user_one_id bigint NOT NULL,
    user_two_id bigint NOT NULL,
    CONSTRAINT ck_conversations_order CHECK ((user_one_id < user_two_id))
);

--
-- Name: conversations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.conversations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conversations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: email_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.email_tokens (
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    type character varying(20) NOT NULL,
    token_hash character varying(64) NOT NULL,
    CONSTRAINT email_tokens_type_check CHECK (((type)::text = ANY ((ARRAY['VERIFY_EMAIL'::character varying, 'RESET_PASSWORD'::character varying])::text[])))
);

--
-- Name: email_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.email_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: follows; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.follows (
    created_at timestamp(6) with time zone NOT NULL,
    followee_id bigint NOT NULL,
    follower_id bigint NOT NULL,
    id bigint NOT NULL
);

--
-- Name: follows_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.follows ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.follows_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: hashtags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hashtags (
    id bigint NOT NULL,
    name character varying(280) NOT NULL
);

--
-- Name: hashtags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.hashtags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hashtags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: likes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.likes (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    post_id bigint NOT NULL,
    user_id bigint NOT NULL
);

--
-- Name: likes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.likes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.likes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.messages (
    conversation_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    read_at timestamp(6) with time zone,
    sender_id bigint NOT NULL,
    content character varying(2000) NOT NULL
);

--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    actor_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    post_id bigint,
    read_at timestamp(6) with time zone,
    recipient_id bigint NOT NULL,
    type character varying(20) NOT NULL,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['FOLLOW'::character varying, 'LIKE'::character varying, 'REPLY'::character varying, 'MENTION'::character varying, 'REPOST'::character varying])::text[])))
);

--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: post_hashtags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_hashtags (
    hashtag_id bigint NOT NULL,
    post_id bigint NOT NULL
);

--
-- Name: post_media; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_media (
    "position" integer NOT NULL,
    id bigint NOT NULL,
    post_id bigint NOT NULL,
    r2_key character varying(255) NOT NULL
);

--
-- Name: post_media_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.post_media ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: post_mentions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_mentions (
    post_id bigint NOT NULL,
    user_id bigint NOT NULL
);

--
-- Name: post_reports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_reports (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    post_id bigint NOT NULL,
    reporter_id bigint NOT NULL,
    reason character varying(255) NOT NULL,
    CONSTRAINT post_reports_reason_check CHECK (((reason)::text = ANY ((ARRAY['SPAM'::character varying, 'HARASSMENT'::character varying, 'HATE_SPEECH'::character varying, 'VIOLENCE'::character varying, 'SEXUAL_CONTENT'::character varying, 'MISINFORMATION'::character varying, 'OTHER'::character varying])::text[])))
);

--
-- Name: post_reports_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.post_reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.posts (
    deleted boolean NOT NULL,
    like_count integer NOT NULL,
    reply_count integer NOT NULL,
    repost_count integer DEFAULT 0 NOT NULL,
    author_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    parent_id bigint,
    quote_of_id bigint,
    repost_of_id bigint,
    root_id bigint,
    reply_policy character varying(20) DEFAULT 'EVERYONE'::character varying NOT NULL,
    content character varying(280) NOT NULL,
    CONSTRAINT posts_reply_policy_check CHECK (((reply_policy)::text = ANY ((ARRAY['EVERYONE'::character varying, 'FOLLOWING'::character varying, 'MENTIONED'::character varying])::text[])))
);

--
-- Name: posts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_tokens (
    revoked boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    token_hash character varying(64) NOT NULL
);

--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: user_reports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_reports (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    reported_user_id bigint NOT NULL,
    reporter_id bigint NOT NULL,
    reason character varying(255) NOT NULL,
    CONSTRAINT user_reports_reason_check CHECK (((reason)::text = ANY ((ARRAY['SPAM'::character varying, 'HARASSMENT'::character varying, 'HATE_SPEECH'::character varying, 'VIOLENCE'::character varying, 'SEXUAL_CONTENT'::character varying, 'MISINFORMATION'::character varying, 'OTHER'::character varying])::text[])))
);

--
-- Name: user_reports_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    email_verified boolean DEFAULT true NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    username character varying(15) NOT NULL,
    status character varying(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    display_name character varying(50) NOT NULL,
    bio character varying(160),
    email character varying(254) NOT NULL,
    avatar_key character varying(255),
    banner_key character varying(255),
    password_hash character varying(255) NOT NULL,
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'DEACTIVATED'::character varying, 'DELETED'::character varying])::text[])))
);

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: blocks blocks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blocks
    ADD CONSTRAINT blocks_pkey PRIMARY KEY (id);

--
-- Name: bookmarks bookmarks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks
    ADD CONSTRAINT bookmarks_pkey PRIMARY KEY (id);

--
-- Name: conversations conversations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT conversations_pkey PRIMARY KEY (id);

--
-- Name: email_tokens email_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_tokens
    ADD CONSTRAINT email_tokens_pkey PRIMARY KEY (id);

--
-- Name: email_tokens email_tokens_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_tokens
    ADD CONSTRAINT email_tokens_token_hash_key UNIQUE (token_hash);

--
-- Name: follows follows_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.follows
    ADD CONSTRAINT follows_pkey PRIMARY KEY (id);

--
-- Name: hashtags hashtags_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hashtags
    ADD CONSTRAINT hashtags_name_key UNIQUE (name);

--
-- Name: hashtags hashtags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hashtags
    ADD CONSTRAINT hashtags_pkey PRIMARY KEY (id);

--
-- Name: likes likes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.likes
    ADD CONSTRAINT likes_pkey PRIMARY KEY (id);

--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);

--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);

--
-- Name: post_hashtags post_hashtags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_hashtags
    ADD CONSTRAINT post_hashtags_pkey PRIMARY KEY (hashtag_id, post_id);

--
-- Name: post_media post_media_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_media
    ADD CONSTRAINT post_media_pkey PRIMARY KEY (id);

--
-- Name: post_mentions post_mentions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_mentions
    ADD CONSTRAINT post_mentions_pkey PRIMARY KEY (post_id, user_id);

--
-- Name: post_reports post_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_reports
    ADD CONSTRAINT post_reports_pkey PRIMARY KEY (id);

--
-- Name: posts posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (id);

--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);

--
-- Name: refresh_tokens refresh_tokens_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_token_hash_key UNIQUE (token_hash);

--
-- Name: blocks uk_blocks_pair; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blocks
    ADD CONSTRAINT uk_blocks_pair UNIQUE (blocker_id, blocked_id);

--
-- Name: bookmarks uk_bookmarks_pair; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks
    ADD CONSTRAINT uk_bookmarks_pair UNIQUE (user_id, post_id);

--
-- Name: conversations uk_conversations_pair; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT uk_conversations_pair UNIQUE (user_one_id, user_two_id);

--
-- Name: follows uk_follows_pair; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.follows
    ADD CONSTRAINT uk_follows_pair UNIQUE (follower_id, followee_id);

--
-- Name: likes uk_likes_pair; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.likes
    ADD CONSTRAINT uk_likes_pair UNIQUE (user_id, post_id);

--
-- Name: post_reports uk_post_reports_pair; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_reports
    ADD CONSTRAINT uk_post_reports_pair UNIQUE (reporter_id, post_id);

--
-- Name: posts uk_posts_repost; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT uk_posts_repost UNIQUE (author_id, repost_of_id);

--
-- Name: user_reports uk_user_reports_pair; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_reports
    ADD CONSTRAINT uk_user_reports_pair UNIQUE (reporter_id, reported_user_id);

--
-- Name: user_reports user_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_reports
    ADD CONSTRAINT user_reports_pkey PRIMARY KEY (id);

--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);

--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);

--
-- Name: idx_blocks_blocked; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_blocks_blocked ON public.blocks USING btree (blocked_id);

--
-- Name: idx_bookmarks_post; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bookmarks_post ON public.bookmarks USING btree (post_id);

--
-- Name: idx_conversations_user_two; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_conversations_user_two ON public.conversations USING btree (user_two_id);

--
-- Name: idx_email_tokens_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_email_tokens_user ON public.email_tokens USING btree (user_id, type);

--
-- Name: idx_follows_followee; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_follows_followee ON public.follows USING btree (followee_id);

--
-- Name: idx_likes_post; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_likes_post ON public.likes USING btree (post_id);

--
-- Name: idx_messages_conversation; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_messages_conversation ON public.messages USING btree (conversation_id, id);

--
-- Name: idx_notifications_recipient; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_recipient ON public.notifications USING btree (recipient_id, id);

--
-- Name: idx_post_hashtags_hashtag; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_post_hashtags_hashtag ON public.post_hashtags USING btree (hashtag_id, post_id);

--
-- Name: idx_post_mentions_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_post_mentions_user ON public.post_mentions USING btree (user_id, post_id);

--
-- Name: idx_posts_author_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_posts_author_id ON public.posts USING btree (author_id, id);

--
-- Name: idx_posts_content_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_posts_content_trgm ON public.posts USING gin (lower((content)::text) public.gin_trgm_ops);

--
-- Name: idx_posts_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_posts_created_at ON public.posts USING btree (created_at);

--
-- Name: idx_posts_parent_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_posts_parent_id ON public.posts USING btree (parent_id, id);

--
-- Name: idx_posts_quote_of; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_posts_quote_of ON public.posts USING btree (quote_of_id);

--
-- Name: idx_posts_repost_of; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_posts_repost_of ON public.posts USING btree (repost_of_id);

--
-- Name: idx_posts_root_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_posts_root_id ON public.posts USING btree (root_id, id);

--
-- Name: idx_refresh_tokens_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_refresh_tokens_user ON public.refresh_tokens USING btree (user_id);

--
-- Name: refresh_tokens fk1lih5y2npsf8u5o3vhdb9y0os; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: post_media fk1urcum9dtf0vgul7k405f4r2d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_media
    ADD CONSTRAINT fk1urcum9dtf0vgul7k405f4r2d FOREIGN KEY (post_id) REFERENCES public.posts(id);

--
-- Name: notifications fk4sd9fik0uthbk6d9rsxco4uja; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk4sd9fik0uthbk6d9rsxco4uja FOREIGN KEY (actor_id) REFERENCES public.users(id);

--
-- Name: messages fk4ui4nnwntodh6wjvck53dbk9m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fk4ui4nnwntodh6wjvck53dbk9m FOREIGN KEY (sender_id) REFERENCES public.users(id);

--
-- Name: notifications fk599539lym3mnkbqks0u806eac; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk599539lym3mnkbqks0u806eac FOREIGN KEY (post_id) REFERENCES public.posts(id);

--
-- Name: conversations fk6fmlr7r40yaqretwu07dt86d4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT fk6fmlr7r40yaqretwu07dt86d4 FOREIGN KEY (user_one_id) REFERENCES public.users(id);

--
-- Name: posts fk6xvn0811tkyo3nfjk2xvqx6ns; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT fk6xvn0811tkyo3nfjk2xvqx6ns FOREIGN KEY (author_id) REFERENCES public.users(id);

--
-- Name: user_reports fk71g2iy5savq929wx5qhgeamne; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_reports
    ADD CONSTRAINT fk71g2iy5savq929wx5qhgeamne FOREIGN KEY (reported_user_id) REFERENCES public.users(id);

--
-- Name: post_reports fk7ccpkj5jys037f9pq98l31ya2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_reports
    ADD CONSTRAINT fk7ccpkj5jys037f9pq98l31ya2 FOREIGN KEY (post_id) REFERENCES public.posts(id);

--
-- Name: bookmarks fk7nbb4ldgek7ux7y6lu0y4g826; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks
    ADD CONSTRAINT fk7nbb4ldgek7ux7y6lu0y4g826 FOREIGN KEY (post_id) REFERENCES public.posts(id);

--
-- Name: email_tokens fk9j2pq9xa8fh246k3uruj9feec; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_tokens
    ADD CONSTRAINT fk9j2pq9xa8fh246k3uruj9feec FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: post_hashtags fkb8j4xx456a7584d8blc604pqg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_hashtags
    ADD CONSTRAINT fkb8j4xx456a7584d8blc604pqg FOREIGN KEY (hashtag_id) REFERENCES public.hashtags(id);

--
-- Name: bookmarks fkdbsho2e05w5r13fkjqfjmge5f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks
    ADD CONSTRAINT fkdbsho2e05w5r13fkjqfjmge5f FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: follows fkeo7hqi2bt2vdwk6mpu0w2ihyb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.follows
    ADD CONSTRAINT fkeo7hqi2bt2vdwk6mpu0w2ihyb FOREIGN KEY (followee_id) REFERENCES public.users(id);

--
-- Name: posts fkg7990ydbap5kvi7ptdju0mxdr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT fkg7990ydbap5kvi7ptdju0mxdr FOREIGN KEY (quote_of_id) REFERENCES public.posts(id);

--
-- Name: post_mentions fkhcl6osasm99cmo3ek9s94cbbb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_mentions
    ADD CONSTRAINT fkhcl6osasm99cmo3ek9s94cbbb FOREIGN KEY (post_id) REFERENCES public.posts(id);

--
-- Name: blocks fkjcracc6rem4ddb6gtkaxhfsvu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blocks
    ADD CONSTRAINT fkjcracc6rem4ddb6gtkaxhfsvu FOREIGN KEY (blocked_id) REFERENCES public.users(id);

--
-- Name: post_mentions fkkj62sfmi7bf1uo1ciqwn73r38; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_mentions
    ADD CONSTRAINT fkkj62sfmi7bf1uo1ciqwn73r38 FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: posts fkklfnv1d8ufdqkrvv5g71txxh3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT fkklfnv1d8ufdqkrvv5g71txxh3 FOREIGN KEY (root_id) REFERENCES public.posts(id);

--
-- Name: blocks fkl05bxnwmimx5n5tsgrgnguvu6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blocks
    ADD CONSTRAINT fkl05bxnwmimx5n5tsgrgnguvu6 FOREIGN KEY (blocker_id) REFERENCES public.users(id);

--
-- Name: posts fklc4ha6e2rf4p04lkf3mk8ivr8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT fklc4ha6e2rf4p04lkf3mk8ivr8 FOREIGN KEY (parent_id) REFERENCES public.posts(id);

--
-- Name: likes fknvx9seeqqyy71bij291pwiwrg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.likes
    ADD CONSTRAINT fknvx9seeqqyy71bij291pwiwrg FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: user_reports fko091kj8ufs63qduxpnbeuefa3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_reports
    ADD CONSTRAINT fko091kj8ufs63qduxpnbeuefa3 FOREIGN KEY (reporter_id) REFERENCES public.users(id);

--
-- Name: post_reports fkqi5fmh45u32i63971en0rmrvo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_reports
    ADD CONSTRAINT fkqi5fmh45u32i63971en0rmrvo FOREIGN KEY (reporter_id) REFERENCES public.users(id);

--
-- Name: follows fkqnkw0cwwh6572nyhvdjqlr163; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.follows
    ADD CONSTRAINT fkqnkw0cwwh6572nyhvdjqlr163 FOREIGN KEY (follower_id) REFERENCES public.users(id);

--
-- Name: notifications fkqqnsjxlwleyjbxlmm213jaj3f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fkqqnsjxlwleyjbxlmm213jaj3f FOREIGN KEY (recipient_id) REFERENCES public.users(id);

--
-- Name: posts fkrheuv39wn7r9kjiy1w6va2gns; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT fkrheuv39wn7r9kjiy1w6va2gns FOREIGN KEY (repost_of_id) REFERENCES public.posts(id);

--
-- Name: post_hashtags fkrrlq793bvaswhomm900i71ac5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_hashtags
    ADD CONSTRAINT fkrrlq793bvaswhomm900i71ac5 FOREIGN KEY (post_id) REFERENCES public.posts(id);

--
-- Name: likes fkry8tnr4x2vwemv2bb0h5hyl0x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.likes
    ADD CONSTRAINT fkry8tnr4x2vwemv2bb0h5hyl0x FOREIGN KEY (post_id) REFERENCES public.posts(id);

--
-- Name: conversations fksjcfd6rwy4gfdgc0ncup74e1p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT fksjcfd6rwy4gfdgc0ncup74e1p FOREIGN KEY (user_two_id) REFERENCES public.users(id);

--
-- Name: messages fkt492th6wsovh1nush5yl5jj8e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fkt492th6wsovh1nush5yl5jj8e FOREIGN KEY (conversation_id) REFERENCES public.conversations(id);

--
-- PostgreSQL database dump complete
--

