CREATE TABLE public.mutes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    muter_id bigint NOT NULL REFERENCES public.users (id),
    muted_id bigint NOT NULL REFERENCES public.users (id),
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_mutes_pair UNIQUE (muter_id, muted_id)
);

CREATE INDEX idx_mutes_muted ON public.mutes USING btree (muted_id);
