ALTER TABLE public.users ADD COLUMN protected_account boolean NOT NULL DEFAULT false;

CREATE TABLE public.follow_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id bigint NOT NULL REFERENCES public.users (id),
    target_id bigint NOT NULL REFERENCES public.users (id),
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_follow_requests_pair UNIQUE (requester_id, target_id)
);

CREATE INDEX idx_follow_requests_target ON public.follow_requests USING btree (target_id);

ALTER TABLE public.notifications DROP CONSTRAINT notifications_type_check;
ALTER TABLE public.notifications ADD CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['FOLLOW'::character varying, 'LIKE'::character varying, 'REPLY'::character varying, 'MENTION'::character varying, 'REPOST'::character varying, 'FOLLOW_REQUEST'::character varying])::text[])));
