-- Photos attached to a direct message (up to 4, in order). A message may have photos and no text; deleting the message removes its rows.
CREATE TABLE public.message_media (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id bigint NOT NULL REFERENCES public.messages(id) ON DELETE CASCADE,
    r2_key character varying(255) NOT NULL,
    "position" integer NOT NULL
);

CREATE INDEX idx_message_media_message ON public.message_media (message_id);
